{"componentChunkName":"component---src-templates-post-jsx","path":"/python-await-vs-return/","result":{"data":{"markdownRemark":{"html":"<p>예전에 담아둔 마음함을 정리하다가 <a href=\"https://jakearchibald.com/2017/await-vs-return-vs-return-await/\">JS에서 <code>await</code>, <code>return</code>, <code>return await</code>의 결과를 비교하는 글</a>을 봤다. 헷갈려 잘못 사용할 수 있는 비동기 함수를 사례별로 구분해 보여주는 좋은 글이었는데 JS에서는 파이썬과 달리 await를 하지 않아도 함수가 실행되는게 당황스러웠다. 언어에 따라 같은 비동기 개념이라도 구현, 사용 방법이 다르구나 느끼면서 파이썬에서는 각각의 경우가 어떻게 동작하는지 정리하고자 한다.</p>\n<h2>재료 준비</h2>\n<p>다음과 같이 반반의 확률로 <code>'통과!'</code> 혹은 에러를 발생하는 함수를 준비했다. 더불어 파이썬에서는 async함수를 REPL에서 await할 수 없고 이벤트 루프를 통해 실행시켜야 하는데 이를 미리 준비해두겠다.</p>\n<blockquote>\n<p>파이썬 3.5 이상에서 작동하는 예제로 3.4에서 실행시키기 위해선 <code>async</code>, <code>await</code> 키워드를 각각 <code>@asyncio.coroutine</code>, <code>yield from</code>으로 바꿔줘야한다.</p>\n</blockquote>\n<pre><code class=\"language-python\">import asyncio\nfrom random import random\n\nasync def toss():\n    await asyncio.sleep(1)\n    if random() > 0.5:\n        raise Exception('에러!')\n    return '통과!'\n\nloop = asyncio.get_event_loop()\n</code></pre>\n<h2>1. 단순 호출</h2>\n<pre><code class=\"language-python\">async def call():\n    try:\n        toss()\n    except:\n        return '잡았다!'\n\nloop.run_until_complete(call())\n# 바로\n# RuntimeWarning: coroutine 'toss' was never awaited\n# None\n</code></pre>\n<p><code>toss</code> 함수를 단순하게 호출하면 런타임경고와 함께 1초의 기다림도 없이 바로 <code>None</code>이 반환된다. <code>toss</code> 함수를 호출하는 순간 파이썬에서는 코루틴 객체를 반환하는데, 이 때는 함수 내부 코드가 실행되지 않는다. 그렇기에 딜레이없이 try 구문을 아무 문제없이 통과하고 명시적인 return 구문이 없어 암묵적으로 <code>None</code>이 반환되었다.</p>\n<p>또한 <code>call</code> 함수는 내부에 await구문이 없으므로 단순 def로 선언해도 되며, 이 땐 런타임경고 없이 항상 <code>None</code>이 반환된다.</p>\n<h2>2. await</h2>\n<pre><code class=\"language-python\">async def call():\n    try:\n        await toss()\n    except:\n        return '잡았다!'\n\nloop.run_until_complete(call())\n# 1초 후\n# None or '잡았다!'\n</code></pre>\n<p><code>toss</code> 함수를 await 구문과 함께 호출하면, 항상 1초를 기다린 후에 반반의 확률로 <code>None</code> 혹은 <code>'잡았다!'</code> 라는 결과를 얻게된다. await 구문을 사용하면 키워드 그대로 async 함수의 결과를 기다린다. 그러면서 <code>toss</code> 내부 코드가 실행되는데 먼저 1초를 기다린다. 만약 앞 선 경우처럼 <code>await</code>가 없다면 <code>asyncio.sleep(1)</code>은 단순히 코루틴만 반환한채 기다림없이 바로 다음 구문이 실행 된다. 이제 반반의 확률로 <code>'통과!'</code>가 반환되거나 <code>Exception('에러!')</code>가 발생한다.</p>\n<ol>\n<li><code>'통과!'</code> 반환: 문제 없이 값이 반환되었으나 <code>call</code> 함수에선 이를 받아주지 않는다. 그렇기에 앞에서 처럼 암묵적인 <code>None</code>이 반환된다.</li>\n<li><code>Exception('에러!')</code> 발생: 발생한 에러가 상위 스택으로 전파된다. 이를 <code>call</code> 내부에서 except로 받아주기 때문에 <code>잡았다!</code>가 반환된다.</li>\n</ol>\n<blockquote>\n<p>예전엔 async/await 개념을 몰라서 \"그냥 <code>time.sleep(1)</code>하면 되는거 아닌가? 어차피 1초 기다리는건 똑같은데\" 처럼 생각했었다. async/await를 사용하면 <code>await asyncio.sleep(1)</code> 구문에서 다른 코루틴으로 스위칭이 발생하므로 <code>asyncio.gather(call(), call())</code>처럼 <code>call</code>함수를 여러번 실행하면 1초 후 결과 하나, 다시 1초 후 결과 하나 이런식이 아니라 1초 후에 결과 두 개를 받아볼 수 있다.</p>\n</blockquote>\n<h2>3. return</h2>\n<pre><code class=\"language-python\">async def call():\n    try:\n        return toss()\n    except:\n        return '잡았다!'\n\nloop.run_until_complete(call())\n# 바로\n# &#x3C;coroutine object toss at 0x10964b518>\n</code></pre>\n<p><code>toss</code> 함수를 await 없이 리턴하면 <code>toss()</code>의 결과인 코루틴 객체가 바로 반환된다. <strong>JS와는 다르게</strong> <code>toss</code> 함수 내부 코드가 실행되지 않으므로 1초의 기다림없이 에러도 발생하지 않고 언제나 코루틴 객체가 바로 반환된다.</p>\n<h2>4. return await</h2>\n<pre><code class=\"language-python\">async def call():\n    try:\n        return await toss()\n    except:\n        return '잡았다!'\n\nloop.run_until_complete(call())\n# 1초 후\n# '통과!' or '잡았다!'\n</code></pre>\n<p><code>toss</code> 함수를 await한 후 리턴하면 1초를 기다린 후 정상적으로 실행된 결과인 <code>'통과!'</code>가 반환되거나 에러가 발생하고 이를 예외로 돌려 <code>'잡았다!'</code>가 반환된다. async 함수를 await 했으므로 2번 처럼 진행되는데, 이번엔 <code>call</code> 함수에서 <code>toss</code> 함수가 반환한 결과를 그대로 반환하므로 <code>None</code>이 반환되지 않는다. 참고로 <code>return await toss()</code> 구문은 다음과 같이 두 줄로 구분해 쓸 수 있다.</p>\n<pre><code class=\"language-python\">async def call():\n    try:\n        result = await toss()\n        return result\n    except:\n        return '잡았다!'\n</code></pre>\n<h2>결론</h2>\n<p>async 함수를 사용할 땐 await를 어디선가 빼먹지 않았는지 신경쓰고, JS와는 동작이 다름에 주의하자. 항상 드는 생각인데 <code>loop.run_until_complete</code>의 shortcut이 생기거나 네이티브 REPL에서 await를 할 수 있으면 좋겠다.</p>\n<blockquote>\n<p><a href=\"https://github.com/vxgmichel/aioconsole\"><code>aioconsole</code></a>, <a href=\"https://github.com/aio-libs/aiomonitor\"><code>aiomonitor</code></a> 라이브러리를 설치하면 확장 REPL에서 await 구문을 사용할 수 있다.</p>\n</blockquote>","frontmatter":{"title":"파이썬의 await vs return vs return await","image":null},"excerpt":"예전에 담아둔 마음함을 정리하다가 JS에서 await, return, return await의 결과를 비교하는 글을 봤다. 헷갈려 잘못 사용할 수 있는 비동기 함수를 사례별로 구분해 보여주는 좋은 글이었는데 JS에서는 파이썬과 달리 await를 하지…"}},"pageContext":{"slug":"python-await-vs-return","date":"2018-06-22","lastmod":"2018-06-22"}},"staticQueryHashes":["269600272","3159585216"],"slicesMap":{}}